name 'elk'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures elasticsearch'
long_description 'Installs/Configures elasticsearch'
version '0.1.0'
chef_version '>= 14.0'

depends 'java', '~> 4.1.0'
depends 'simple-logstash', '~> 1.0.2'
depends 'elasticsearch', '~> 4.0.6'
